name: hotfix-release-please

on:
  push:
    branches:
      - hotfix

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v4
        with:
          release-type: go
          package-name: go-api-now
          default-branch: hotfix
