name: hotfix-release-please

on:
  push:
    branches:
      - hotfix

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4 # v4
        with:
          release-type: go
          package-name: go-api-now
          default-branch: hotfix
