name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: '1.21.0'
  IMAGE_NAME: 'go-api-now'

jobs:
  build:
    name: Build and Run the test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version: '${{ env.GO_VERSION }}'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

  docker:
    name: Build the container image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2

    - name: Login to GHCR
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
      with:
        push: false
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
